language: python
python:
  - "2.7"
install:
  - sudo apt-get update
  - sudo apt-get install -y --force-yes libsdl-dev
  # sdformat dependencies
  - sudo apt-get install -y --force-yes libtinyxml-dev
  # Gazebo dependencies
  - sudo apt-get install -y --force-yes libboost-all-dev libprotoc-dev libprotobuf-dev protobuf-compiler libqt4-dev libtar-dev
  - source use_repo.sh
script:
  - py.test -s
