language: python
python:
  - "2.7"
cache:
  apt: true
install:
  - sudo apt-get update
  - sudo apt-get install -y --force-yes libsdl-dev
  # sdformat dependencies
  - sudo apt-get install -y --force-yes libtinyxml-dev
  # primesense dependencies
  - sudo apt-get install -y libusb-1.0.0-dev libudev-dev graphviz doxygen
  # Gazebo dependencies
  - sudo apt-get install -y --force-yes build-essential libboost-all-dev pkg-config
  - sudo apt-get install -y --force-yes libprotoc-dev libprotobuf-dev protobuf-compiler libqt4-dev libtar-dev
  - sudo apt-get install -y --force-yes libcurl4-openssl-dev libcegui-mk2-dev libtbb-dev
  - sudo apt-get install -y --force-yes libswscale-dev libavformat-dev libavcodec-dev libogre-dev
  - sudo apt-get install -y --force-yes libgts-dev libltdl3-dev playerc++ libxml2-dev libfreeimage-dev freeglut3-dev
  - sudo apt-get install -y --force-yes python-gst0.10 python-cairo python-gobject-2
  - source use_repo.sh
script:
  - "./test"
